Add scale-setter
open-pioneer/trails-openlayers-base-packages pull request #332
Opened 2024-07-11 10:02 UTC by rolfp01

Issue: #72

2024-07-15 07:48 UTC, mbeckem commented on src/packages/scale-setter/CHANGELOG.md
Looks like you also executed `pnpm version` here -- that is not necessary. Since this is the very first version of the package, the `CHANGELOG.md` should be empty (except for the package name).

Simply use `pnpm changeset` to create a changeset file (see [contribution guide](https://github.com/open-pioneer/trails-starter/blob/main/docs/Contributing.md#creating-a-pull-request)). You can also downgrate the package in your package.json to `0.0.1` (or something else below `0.1.x`) so the initial `minor` release automatically gets the version `0.1.0`

2024-07-15 09:23 UTC, mathe05 commented on src/packages/scale-setter/README.md
> +Setting property `mapZoomScales` to an int[], options in the select will be set to given. By default the zoomlevels are the stanrd levels by adv
Typo: stanrd -> standard

I would suggest to replace the long URL with a link with a title:

`
By default the zoom levels are the [standard levels by AdV](https://www.adv-online.de/AdV-Produkte/Standards-und-Produktblaetter/AdV-Profile/binarywriterservlet?imgUid=36060b99-b8c4-0a41-ba3c-cdd1072e13d6&uBasVariant=11111111-1111-1111-1111-111111111111).
`

2024-07-15 09:26 UTC, mathe05 commented on src/packages/scale-setter/README.md
> +    mapZoomScales={[
In my opinion, "mapZoomScales" sounds a bit unnecessarily repated. Maybe just simply "scales"? What do you think @mbeckem?

2024-07-15 09:31 UTC, mathe05 commented on src/packages/scale-setter/index.ts
> +export type { ScaleSetterProps } from "./ScaleSetter";
@mbeckem Is there any preferred code style for exports in this project? Some packages use this version in separate lines, others [combine everything in one line](https://github.com/open-pioneer/trails-openlayers-base-packages/blob/main/src/packages/editing/index.ts).

2024-07-15 11:49 UTC, mathe05 commented on src/packages/scale-setter/ScaleSetter.test.tsx
> +// SPDX-FileCopyrightText: 2023 Open Pioneer project (https://github.com/open-pioneer)
Maybe add some more tests to verify the correct behaviour?

* when changing the selection: is the map scale updated correctly and the label of the select updated to the selected value?
* when the map scale changes after the component was created, is the label of the select updated to the new value?
* are the default values used when no property is set? and vice versa
* are all configured scale values available in the select?

2024-07-16 10:33 UTC, mbeckem commented on src/packages/scale-setter/index.ts
> +export type { ScaleSetterProps } from "./ScaleSetter";
It shouldn't matter in practice, but I prefer to have a single import/export per module if possible.

2024-07-16 10:35 UTC, mbeckem commented
I didn't have the time to do a full review yet. Looks like Alexander already left a bit of feedback. I'll try to take a look this afternoon.

2024-07-16 14:32 UTC, mbeckem requested changes

2024-07-16 14:32 UTC, mbeckem commented on src/packages/scale-setter/README.md
> +    mapZoomScales={[
I like `scales`, `choices` or `scaleChoices` (or options instead of choices). A `*choice` could also support other properties in the future, as an extension (e.g. a custom title if the raw number is not sufficient).

Also, the README should refer to this as a `number[]` (or just as an "array of numbers" as text) instead of an `int[]`, since JavaScript/TypeScript has no concept of those.

2024-07-16 14:32 UTC, mbeckem commented on src/packages/scale-setter/ScaleSetter.tsx
> +                1 : {intl.formatNumber(sc)}
This should be a helper function (i.e. `renderDisplayScale(intl, rawScale): string`). There are two more repetitions below

2024-07-16 14:32 UTC, mbeckem commented on src/packages/scale-setter/ScaleSetter.tsx
I noticed two major problems with the current approach.

1. The scale can be incorrect depending on the current map projection and the location on that map.
   
   I included the scale setter in the showcase app (in your branch) so you can check it out locally.
   When attempting to change the scale near the equator, it will be applied correctly (within a small margin of error).
   When trying to do the same for example in the very north of Canada, the final scale will be drastically different from the actually selected one.

   The likely reason is that the code does not consider the point resolution at the _current center_ of the view port.
   See for example the implementation of the [useScale](https://github.com/open-pioneer/trails-openlayers-base-packages/blob/61b45f9552c8678e9dfa0156a102f84c0a22af83/src/packages/map/ui/hooks.ts#L79) hook, which, to my knowledge, works correctly.

   The key difference is the call to  `getPointResolution(projection, resolution, center)`.
   In my opinion, your code needs the _reverse_ of that function: the scale setter actually selects the current _point_ resolution and we want to change the map's resolution value.

2. The `<select>` widget correctly shows the current scale of that map, even if that scale is not part of the pre-defined scale options (which is nice).
   However, because there is never a matching `<option>` for the current `value` of the `<select>`, the browser appears to (?) create an anonymous option itself (I didn't know that was possible).

   The problem with this is that you can no longer use the arrow keys (up / down) to change the current value of the `<select>`.
   This works fine for other selects in the demo app, e.g. the select to change the current demo.

   I believe the following approach would be better (i have not tested it myself, tho):

   - Always use the raw numeric scale value for the select's `value` (it currently uses the display value)
   - Use the same numeric scale value for the value of each `option`
   - The important part: if there is no option for the _current_ scale (which is usually the case), create one and render it too.
     The options in the `<select>` should be sorted, this way you can use `up` and `down` to move between the options.

     This approach can probably use some refinement. For example, if one does not "hit" one of the predefined scale options _precisely_, there will be an annoying
     additional option that is _almost_ equal to the previous (or next) one.
     Perhaps some rounding or relative error margin (e.g. 10%) could be used here to skip the creation of the additional option and use the close one instead.

    As an alternative, you could also consider simplifying the design.
    Instead of showing the precise current scale, you could simply pick the _closest_ predefined option and activate _that_ instead.
    This loses the accurate display logic, of course, but it might still be good enough.

2024-07-16 14:32 UTC, mbeckem commented on src/packages/scale-setter/ScaleSetter.tsx
> +        if (tempView != undefined) map?.olMap.setView(tempView);
The `setView` call is redundant, I believe. `setResolution(..)` already has the desired side effect.

2024-07-17 07:01 UTC, mbeckem commented on src/packages/scale-setter/ScaleSetter.tsx
I thought about point 2 some more, so here are more alternatives:

- Use an "autocomplete" approach instead: A (read-only, i.e. not user-editable) field that shows the current scale, and a dropdown that allows selection of predefined scale values. This way there is no relation between the current scale and the options, except for the "click option -> change scale" interaction. `React-Select` should (?) support this approach.
- Completely separate the current scale and the options. One can use the ScaleViewer to show the current scale. The scale setter would only support setting the scale. This can be done by using a different UI component, such as chakra`s Menu. The ScaleSetter would render a simple menu button ("change scale") which opens a menu of choices.

2024-07-19 16:20 UTC, mathe05 commented on src/packages/scale-setter/ScaleSetter.tsx
> Completely separate the current scale and the options. One can use the ScaleViewer to show the current scale. The scale setter would only support setting the scale. This can be done by using a different UI component, such as chakra`s Menu. The ScaleSetter would render a simple menu button ("change scale") which opens a menu of choices.

This solution has the disadvantage that it requires two UI widgets, which means more space. This is not ideal on mobile devices.

As a user I would also prefer the combined solution. I find it confusing to separate the manipulation of a value from its display.

2024-07-20 11:34 UTC, mbeckem commented on src/packages/scale-setter/ScaleSetter.tsx
I think the best option is using a `<Menu />` (or  `Button` + `Popover`). Using the native `Select` is a bad idea because the current value is very likely not included in the predefined options. A button with a Menu does not have this problem. Just render the current scale in the button and, on clicking the button, show the available options.

2024-08-01 07:03 UTC, rolfp01 commented
In den Browser the map automatically zooms to the nearest available scale and updates the scale viewer etc. In the tests it seems like the map can do every scale. For example i select 8000 as scale and the map is exactly on that scale, when in the browser only 8507 is available.
@mbeckem do you have any idea why and what i can do about that?

2024-08-01 07:19 UTC, mbeckem commented
> In den Browser the map automatically zooms to the nearest available scale and updates the scale viewer etc. In the tests it seems like the map can do every scale. For example i select 8000 as scale and the map is exactly on that scale, when in the browser only 8507 is available. @mbeckem do you have any idea why and what i can do about that?

@rolfp01 Do you mean that you can't reach the precise scale 8000 via mouse scrolling in the browser? Maybe OpenLayers has an option to configure fixed zoom levels that fit your predefined scale settings.

2024-08-01 07:50 UTC, rolfp01 commented
> > In den Browser the map automatically zooms to the nearest available scale and updates the scale viewer etc. In the tests it seems like the map can do every scale. For example i select 8000 as scale and the map is exactly on that scale, when in the browser only 8507 is available. @mbeckem do you have any idea why and what i can do about that?
> 
> @rolfp01 Do you mean that you can't reach the precise scale 8000 via mouse scrolling in the browser? Maybe OpenLayers has an option to configure fixed zoom levels that fit your predefined scale settings.

I mean the exact opposite. I guess its right that OpenLayers can not some exactly to 8000, but in the tests it can

2024-08-01 08:10 UTC, mbeckem commented
> > > In den Browser the map automatically zooms to the nearest available scale and updates the scale viewer etc. In the tests it seems like the map can do every scale. For example i select 8000 as scale and the map is exactly on that scale, when in the browser only 8507 is available. @mbeckem do you have any idea why and what i can do about that?
> > 
> > 
> > @rolfp01 Do you mean that you can't reach the precise scale 8000 via mouse scrolling in the browser? Maybe OpenLayers has an option to configure fixed zoom levels that fit your predefined scale settings.
> 
> I mean the exact opposite. I guess its right that OpenLayers can not some exactly to 8000, but in the tests it can

This might be related to the fact that the map isn't actually being "rendered" in your test (no `<MapContainer />`).

Note that even it were rendered, the behaviour would still likely differ from the real browser behavior. There is often no good way to test advanced OpenLayers features in our mocked DOM setup. For that, we would need to run the tests in an actual browser. This is actually something we could do in the future, because Vitest is now starting to support [Browser Tests](https://vitest.dev/guide/browser/). Note that there is a performance trade-off: running tests in Node is cheap and simple (but sometimes not precise) while browser tests are slower and complicated. Most tests should run inside Node.

2024-08-01 08:13 UTC, mbeckem commented
I made two changes to your branch: 
- I've made the menu lazy and wrapped its content into a `<Portal>`. The Portal is one way to allow the content to "escape" its parent container (otherwise, it can be cut off if the parent is small). The other way is configuring `strategy: fixed`, but i forgot what the trade-offs are. Making it lazy means that the contents are only created once the button is clicked, which slightly improves performance.
- In tests, please don't `return` when your expected preconditions are not met (e.g. if an option is not available or if the map does not have a center). If your tests return without an error they will _pass_ silently, but they shoud _fail_ in these circumstances.  If you see existing test code doing that it should be fixed instead.

2024-08-02 12:17 UTC, mathe05 commented on src/packages/scale-setter/ScaleSetter.test.tsx
> +// SPDX-FileCopyrightText: 2023 Open Pioneer project (https://github.com/open-pioneer)
The added tests look good!

I would suggest to merge the tests `should successfully update the label when selection changes` and `should successfully update the map scale when selection changes` as they are equal except for the `expect` statement.

And I think you still have no test for this:

> when the map scale changes after the component was created, is the label of the select updated to the new value?

2024-08-06 06:29 UTC, rolfp01 commented
I also created a branch with a scale-select. It combines the scale setter with the scale input. Which one do you prefer to use @mbeckem ?

2024-08-06 06:37 UTC, rolfp01 reviewed
I added the requestes tests and behaviour to the scale-setter

2024-08-06 07:10 UTC, mbeckem commented
@rolfp01 I'd like to do a final review and merge this. Is this ready or are you actively working on it?

2024-08-06 07:14 UTC, mbeckem commented
> I also created a branch with a scale-select. It combines the scale setter with the scale input. Which one do you prefer to use @mbeckem ?

I'd like to focus on this PR first. Is this one ready to merge? I'd like to a final review today.

2024-08-06 07:51 UTC, rolfp01 commented
> > I also created a branch with a scale-select. It combines the scale setter with the scale input. Which one do you prefer to use @mbeckem ?
> 
> I'd like to focus on this PR first. Is this one ready to merge? I'd like to a final review today.

Both the scale setter and select are ready to merge. i guess its better to use the scale select, to have just one component, but the decision is yours ;)

2024-08-06 10:32 UTC, mbeckem approved these changes

2024-08-06 10:43 UTC, merged