Feature/access measurements
open-pioneer/trails-openlayers-base-packages pull request #342
Opened 2024-07-30 07:28 UTC by arnevogt

extends Measurement component to allow access to current measurements 

- add optional property `predefinedMeasurements `to Measurement component
  - allows to render predefined measurement geometries in the same style as user created measurements
- add optinal property `measurementsHandler `to Measurement component
  - optinal event handler which is called when measurments are added or removed

2024-07-30 07:33 UTC, arnevogt commented on src/packages/measurement/MeasurementController.ts
> +        }
Alternatively, I could simply remove all existing predefined measurements and add all geometries.  
Though, it would create more events (and you could end up with infinite recursions if you use `measurementHandler` _carelessly_.

2024-07-30 15:01 UTC, mathe05 commented on src/packages/measurement/README.md
> +### add predefined measurments
Here and in the following lines are some typos: `measurment `-> `measurement`

2024-07-30 15:04 UTC, mathe05 commented on src/packages/measurement/Measurement.tsx
> +        predefinedMeasurments
Typos?

2024-07-30 15:06 UTC, mathe05 commented on src/packages/measurement/Measurement.tsx
> +    predefinedMeasurments?: MeasurementGeometry[];
Typo?

2024-07-30 15:55 UTC, mathe05 commented on src/packages/measurement/MeasurementController.ts
> +        }
Your solution is better because it avoids emitting unnecessary events. But I think for the typical use case of predefined measurements the simple solution would be sufficient. The typical use case is to provide predefined measurements only once on startup to restore a previous app state. In this case, there are no existing geometries, so the filtering is unnecessary, there would not be any `remove-measurement` emitted, only `add-measurement` events for the provided geometries.

2024-08-06 12:20 UTC, mbeckem requested changes

2024-08-06 12:20 UTC, mbeckem commented on src/packages/measurement/MeasurementController.ts
>  export type MeasurementType = "area" | "distance";
These types should move into the `Measurement.tsx` (next to the props). They're part of the react component's public interface (even if they _happen_ to be used here primarily).

2024-08-06 12:20 UTC, mbeckem commented on src/packages/measurement/MeasurementController.ts
> +        this.source.on(["addfeature", "removefeature"], (e) => {
I think there should be two kinds of events emitted from this controller, and no more:
- A measurement is added via _user interaction_ ("add-measurement").
- Measurements are removed via _user interaction_ (either a combined "clear" event or multiple "remove-measurement" events). 

Consequently there _should not_ be events when the predefined measurements change. All we're doing is applying the state that the caller has _told_ us to apply. There is no "change" to propagate.

I recommend separating the code paths a bit, and not to rely on vector source events. Instead, the events should be emitted explicitly when the user finishes the draw interaction or clicks the clear button. The code to create the measurements / features should still be reused, of course.

2024-08-06 12:20 UTC, mbeckem commented on src/packages/measurement/Measurement.tsx
> +    measurementsHandler?: MeasurementsChangedHandler;
Should be called `onChange` or `onMeasurementsChange`, since this is an event handler.

2024-08-06 12:20 UTC, mbeckem commented on src/packages/measurement/Measurement.tsx
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
These comments seem to be obsolete.

2024-08-06 12:20 UTC, mbeckem commented on src/packages/measurement/MeasurementController.ts
>  export class MeasurementController {
I'm just thinking out aloud here.

Currently the controller and the react props are very "low level". A "Measurement" _is_ a geometry of a certain type and nothing more. I believe it could help make the implementation of the controller more readable if we introduced actual `Measurement` objects that could be used to track the state (geometry [if complete], size [or incomplete], the tooltip (if any), perhaps an id and so on). Much of the controller would then be responsible for managing the current `Measurement` instances and only the low level bits would have to translate them into concrete features / draw interactions. 

Some of the information available within the internal `Measurement` objects could also be passed to the users through the event handler (for example, the measured size). In the future, measurements could also have a `label` or a `timestamp` or at least an `id` (if we need fine grained management capabilities, i.e. removal of not all but only certain measurements).

2024-08-06 13:09 UTC, arnevogt commented on src/packages/measurement/MeasurementController.ts
> +        this.source.on(["addfeature", "removefeature"], (e) => {
If I understand correctly, it would still be necessary to raise "remove-measurement" events* for predefined measurements when the user clicks the clear button.
Or do you think predefined measurements should remain even when the user clicks the clear button?

*I think multiple events are preferable because it allows accessing the actual measurement in the event handler.

2024-08-06 13:31 UTC, mbeckem commented on src/packages/measurement/MeasurementController.ts
> +        this.source.on(["addfeature", "removefeature"], (e) => {
True, the remove event should be fired in that case.

I'm trying to plan ahead for a future requirement: where the user can not only add predefined measurements, but can also _remove_ certain measurements. The "React way" to that would be to offer a controlled API (e.g. prop `measurements` which would tell our widget what to render precisely). Combined with the existing event handler this would work:
- uncontrolled usage: the currently implemented mode, can use the event handler to subscribe to changes (these are essentially "FYIs")
- controlled usage: the user must implement the handler and the measurement props. If one wants to delete a certain measurement, one can just remove it from the array and re-render.

So i think your current approach is actually fine. However, the implementation should better call the handlers explicitly still instead of wrapping the ol source events. Feels like a violation of _separation of concerns_ to me. Especially because the layer is essentially public (via the map) and people could add / remove features from our _internal_ layer, producing invalid events. I don't want people to rely on something like that.

2024-08-08 07:56 UTC, arnevogt commented on src/packages/measurement/MeasurementController.ts
> +        this.source.on(["addfeature", "removefeature"], (e) => {
The handlers are now called when the user finishes a measurement or clears  all measurements, not when features are added/removed.

I am unsure if it should really raise events for added predefined measurements. The main purpose of the add/remove events is to track changes. It certain that the predefined measurements are rendered anyway.
If we need the events for a "uncontrolled mode", we would only have to add one line of code

2024-08-08 07:59 UTC, arnevogt commented on src/packages/measurement/MeasurementController.ts
>  export class MeasurementController {
Is this something you envision for this PR?

I think this (e.g. accessing and manipulating tooltips) would only have a real benefit if the component supported an "uncontrolled mode". (see comments above)

2024-08-30 10:24 UTC, merged