Simplify usage of mapIds
open-pioneer/trails-openlayers-base-packages pull request #349
Opened 2024-09-05 10:42 UTC by mbeckem

Based on user feedback: usage of explicit `mapId` is repetetive and inconvenient since most applications use a single map.

This PR introduces the `DefaultMapProvider` that allows you to configure a (default) map for an entire subtree of components.
In this case, the `mapId` parameter can be omitted, unless one wishes to use a different map (explicit map id on a component always overrides any inherited defaults).

This approach gets rid of the repetetiveness in the React UI part of an application (see updated example applications).

Example:

```tsx
import { DefaultMapProvider } from "@open-pioneer/map";

<DefaultMapProvider mapId={MAP_ID}>
    {/* no need to repeat the map id in this subtree, unless you want to use a different one */}
    <MapContainer />
    <Toc />
    <ComplexChild />
</DefaultMapProvider>;
```

This PR also implements support for explicit `map` props on all components (as an alternative to `mapId`).

2024-09-23 09:09 UTC, antoniave requested changes

2024-09-23 09:09 UTC, antoniave commented on src/packages/map/ui/DefaultMapProvider.tsx
> + * Note that you can also use a direct reference to the map model as an alternative to the id.
An alternative is mentioned before the "standard" is introduced. Maybe just mention both possibilities as equally valid alternatives?

2024-09-23 09:09 UTC, antoniave commented on src/packages/map/ui/MapContainer.tsx
> +    const map = modelState.map;
In my opinion it is better to use "mapModel" as a variable name. I always think about the olMap if I only read "map".

2024-09-23 09:09 UTC, antoniave commented on src/packages/map/ui/useMapModel.test.tsx
> +it("returns the immediately configured map model when specified", async () => {
when --> if ?

2024-09-23 09:09 UTC, antoniave commented on src/packages/map/ui/useMapModel.ts
> +export function useMapModel(props?: undefined | string | MapModelProps): UseMapModelResult {
If I pass a MapModel as a parameter (not allowed by TS, but possible in JS), the hook returns an empty object. In my opinion it should return an error or an valid result.

2024-09-23 09:59 UTC, mbeckem commented on src/packages/map/ui/MapContainer.tsx
> +    const map = modelState.map;
Using `map` for an instance of `MapModel` is also done in the props of the new `DefaultMapProvider` and `useMapModel`:

```ts
export interface MapModelProps {
    /**
     * The id of the map.
     * The map will be looked up in the MapRegistry service.
     */
    mapId?: string | undefined;

    /**
     * The direct map model reference to use.
     * This property can be used as an alternative to the {@link mapId}.
     */
    map?: MapModel | undefined;
}
```

I believe `map` and `olMap` are different enough (i think there is also precedent for this naming in other packages).

2024-09-23 10:00 UTC, mbeckem commented on src/packages/map/ui/useMapModel.test.tsx
> +it("returns the immediately configured map model when specified", async () => {
Done, see incoming commit.

2024-09-23 10:01 UTC, mbeckem commented on src/packages/map/ui/useMapModel.ts
> +export function useMapModel(props?: undefined | string | MapModelProps): UseMapModelResult {
Are you sure? I've added a test that passes a mock map model directly to the hook. The hook throws an exception (the unexpected parameter is treated the same as an empty object). So passing garbage arguments to the hook will either return the default map model (if present in the component hierarchy) or thrown an error.

2024-09-23 10:02 UTC, mbeckem commented on src/packages/map/ui/DefaultMapProvider.tsx
> + * Note that you can also use a direct reference to the map model as an alternative to the id.
Done, see incoming commit

2024-09-23 11:36 UTC, antoniave commented on src/packages/map/ui/useMapModel.ts
> +export function useMapModel(props?: undefined | string | MapModelProps): UseMapModelResult {
The error is not thrown if an DefaultMapProvider is used.

Example: Update test with the following wrapper: 
```ts 
 wrapper: (props) => (
                <PackageContextProvider services={services} {...props}>
                    <DefaultMapProvider map={mapModel}>{props.children}</DefaultMapProvider>
                </PackageContextProvider>
            )
```

2024-09-23 11:42 UTC, mbeckem commented on src/packages/map/ui/useMapModel.ts
> +export function useMapModel(props?: undefined | string | MapModelProps): UseMapModelResult {
True, but I don't think that we can catch that in general (arbitrary objects are allowed, as are objects without any of the "mapId" or "map" parameters). However, we could introduce a special case for _just_ instances of MapModel (via `instance of`) and return the map model directly.

2024-09-23 14:54 UTC, mbeckem commented on src/packages/map/ui/useMapModel.ts
> +export function useMapModel(props?: undefined | string | MapModelProps): UseMapModelResult {
I've included the mentioned special case, see tests.

2024-09-26 08:36 UTC, antoniave approved these changes

2024-09-26 10:10 UTC, merged